# templates/route.yml
# Validar si es necesario definir la route en el values.yml o cada service necesita tener una ruta? dentro de la definicion del service, puede especificarse el nombre de la ruta, y de existir ese valor, se creara la ruta  
{{- if .Values.route }}
{{- range $route := .Values.route }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: '{{ $.Values.name }}'
  name: '{{ $.Values.name }}'
spec:
  {{- if $route.host }}
  host: {{ $route.host }}
  {{- end }}
  {{- if $route.path }}
  path: {{ $route.path }}
  {{- end }}
  port:
    targetPort: {{ $route.targetPort }}
  to:
    kind: Service
    name: {{ $.Values.name }}
    weight: 100
  wildcardPolicy: None
{{- end }}
{{- end }}