apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app:  {{ .Values.name }}
    service: {{ .Values.name }}
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    {{- if .Values.service }}
    {{- range $svc := .Values.service }}
  - name: {{ $svc.port }}-tcp
    port: {{ $svc.port }}
    protocol: TCP
    targetPort: {{ $svc.targetPort }}
    {{- end }}
    {{- end }}
  selector:
    deployment: {{ .Values.name }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}